### ISSUE TITLE
Problem with the validation of config.xml files

### ISSUE THREAD

**Issue by dikim33** [oscar-cluster/oscar#360]
**Reported by valleegr on 28 Jul 2007 05:24 UTC**
It seems that the XML validation does not check if the 'uri' tag exists or not. However, if the tag does not exist, opkgc fails:

```
[INFO] Generates /tmp/opkgs/opkg-apitest/debian/.control.tmpl from template /usr/local/share/opkgc/tmpl/debian/.control.tmpl.swp
Traceback (most recent call last):
  File "/usr/local/bin/opkgc", line 125, in ?
    main()
  File "/usr/local/bin/opkgc", line 122, in main
    c.compile(build)
  File "/usr/local/lib/python2.4/site-packages/Opkgc/OpkgcCompiler.py", line 304, in compile
    self.cheetahCompile(desc, template, os.path.join(debiandir, base))
  File "/usr/local/lib/python2.4/site-packages/Opkgc/OpkgcCompiler.py", line 64, in cheetahCompile
    f.write(t.respond())
  File "_usr_local_share_opkgc_tmpl_debian__control_tmpl_swp.py", line 87, in respond
  File "/usr/local/lib/python2.4/site-packages/Opkgc/OpkgDescription.py", line 83, in node
    s = p.sub(' ', self.xmldoc.findtext(path))
TypeError: expected string or buffer
```

If i add a 'uri' tag, it works fine.

**Comment by dikim33** [comment]
**Modified by valleegr on 28 Jul 2007 05:33 UTC**

**Comment by dikim33** [comment]
**Comment by jparpail on 6 Aug 2007 13:20 UTC**
Duplicate of Ticket #352 which is fixed by r6037
