### ISSUE TITLE
Problem with the --supported-dist option of OPKGC

### ISSUE THREAD

**Issue by dikim33** [oscar-cluster/oscar#447]
**Reported by valleegr on 4 Jan 2008 21:38 UTC**
Debian system, opkgc installed from the debian package.

```
$ opkgc --version
opkgc 0.4
```

```
$ dpkg -l | grep opkgc
ii  opkgc 0.4-1 Transform OSCAR Package into .deb or RPM
```

I have the following error:

```
$ opkgc --supported-dist
Supported target distributions are:
Traceback (most recent call last):
  File "/usr/local/bin/opkgc", line 141, in ?
    main()
  File "/usr/local/bin/opkgc", line 108, in main
    distList()
  File "/usr/local/bin/opkgc", line 72, in distList
    for target in eval(compiler).SupportedDist():
AttributeError: class RPMCompiler has no attribute 'SupportedDist'
```

**Comment by dikim33** [comment]
**Modified by valleegr on 4 Jan 2008 21:38 UTC**

**Comment by dikim33** [comment]
**Comment by dikim on 4 Jan 2008 22:05 UTC**
Hi Geoffroy,

I think this was fixed long times ago (about one month ago).
Are you using trunk of opkgc or its tarball? Anyway, you have to use its trunk version and it is very stable now.
http://svn.oscar.openclustergroup.org/trac/oscar/changeset/6614

Regards,

- DongInn

**Comment by dikim33** [comment]
**Comment by jparpail on 7 Feb 2008 13:38 UTC**
Fixed in rev6614
