### ISSUE TITLE
apitest fails to run utf-8 encoded test scripts

### ISSUE THREAD

**Issue by dikim33** [oscar-cluster/oscar#656]
**Reported by olahaye74 on 26 Feb 2014 09:23 UTC**
apitest fails to parse and run test scripts that are encoded in utf-8 eventough the 1st lines sets the encoding to utf-8:
<?xml version="1.0" encoding="utf-8"?>

The result is the following. Not that apitest then hangs (no exit).
Unhandled Error
Traceback (most recent call last):
  File "/usr/bin/apitest", line 162, in start
    self.start_cmdLine()
  File "/usr/bin/apitest", line 297, in start_cmdLine
    reactor.run()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1169, in run
    self.mainLoop()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1178, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 800, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/site-packages/libapitest/jobManager.py", line 114, in poll
    self.do_task()
  File "/usr/lib/python2.7/site-packages/libapitest/jobManager.py", line 126, in do_task
    self.Execute()
  File "/usr/lib/python2.7/site-packages/libapitest/jobManager.py", line 244, in Execute
    tH.prepare(task)
  File "/usr/lib/python2.7/site-packages/libapitest/libapitest.py", line 302, in prepare
    self.load(testFileName)
  File "/usr/lib/python2.7/site-packages/libapitest/libapitest.py", line 384, in load
    self.xmlFileTree  = ElementTree.parse(self.testFileName)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1183, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 19, column 49

**Comment by dikim33** [comment]
**Modified by olahaye74 on 26 Feb 2014 09:25 UTC**

**Comment by dikim33** [comment]
**Modified by olahaye74 on 26 Feb 2014 09:25 UTC**
