### ISSUE TITLE
apitest crash if a dependance in a batch script is not found.(File not found)

### ISSUE THREAD

**Issue by dikim33** [oscar-cluster/oscar#657]
**Reported by olahaye74 on 26 Feb 2014 10:09 UTC**
apitest crashes in a batch script contains a dep that is not found and ran from a directory which is not the torque_validate.apb (in the example below)

In the following testcase test, the line oscar_tst_user.apt was not found (ran from the svn).
```
cd ~svn/oscar/packages/torque/testing
apitest -T -v -f apitests.d/torque_validate.apb
```

The crash output is:
```
Could not parse 'apitests.d/torque_validate.apb'.

Unhandled Error
Traceback (most recent call last):
  File "/usr/bin/apitest", line 162, in start
    self.start_cmdLine()
  File "/usr/bin/apitest", line 297, in start_cmdLine
    reactor.run()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1169, in run
    self.mainLoop()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1178, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 800, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/site-packages/libapitest/jobManager.py", line 114, in poll
    self.do_task()
  File "/usr/lib/python2.7/site-packages/libapitest/jobManager.py", line 126, in do_task
    self.Execute()
  File "/usr/lib/python2.7/site-packages/libapitest/jobManager.py", line 258, in Execute
    tB.loadBatchFile(task)
  File "/usr/lib/python2.7/site-packages/libapitest/jobManager.py", line 388, in loadBatchFile
    batchFileTreeRoot = self.batchFileTree.getroot()
exceptions.AttributeError: 'NoneType' object has no attribute 'getroot'
```

The output should be: FAILED: oscartst_user.apt not found or something similar.

**Comment by dikim33** [comment]
**Modified by olahaye74 on 26 Feb 2014 10:09 UTC**

**Comment by dikim33** [comment]
**Modified by olahaye74 on 26 Feb 2014 10:10 UTC**

**Comment by dikim33** [comment]
**Modified by olahaye74 on 26 Feb 2014 10:56 UTC**

**Comment by dikim33** [comment]
**Modified by olahaye74 on 26 Feb 2014 10:56 UTC**
