### ISSUE TITLE
apitest: reg exp "[ERROR.*" crashes apitest. ("[" not supported in regexp)

### ISSUE THREAD

**Issue by dikim33** [oscar-cluster/oscar#661]
**Reported by olahaye74 on 7 Mar 2014 16:04 UTC**
<output name="stdout" format="regexp">[apitest in the following way:
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1178, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 800, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 362, in callback
    self._startRunCallbacks(result)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 458, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 545, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/site-packages/libapitest/libapitest.py", line 698, in procReturned
    self.validate()
  File "/usr/lib/python2.7/site-packages/libapitest/libapitest.py", line 575, in validate
    rmatch = re.compile(self.expect[k](ERROR.*</output>
Crashes)[1],re.M|re.S)
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression

Need to CTRL-C to get back to shell prompt.

The problem is the "[" in the regexp.
=> Should not crash.
=> Should just print ERROR; invalid regexp and exit cleanly.

**Comment by dikim33** [comment]
**Modified by olahaye74 on 7 Mar 2014 16:04 UTC**
